add Home page
awesomesk1ll/gotfilm.tk pull request #13
Opened 2021-03-26 10:00 UTC by TamaraBogantseva

Home page + custom Search icon

2021-03-26 14:18 UTC, awesomesk1ll requested changes
Посмотри пожалуйста по комментариям.

2021-03-26 14:18 UTC, awesomesk1ll commented on frontend/src/components/ThemeButton.jsx
> +      style={ {
Напрашивается класс + вынесение стилей стилей по методу, который мы обсуждаем. sass/scss ?

2021-03-26 14:18 UTC, awesomesk1ll commented on frontend/src/pages/Home/style.scss
> +      fill: #DA952D;
Такие вещи как цвета предлагаю вынести в $variable перменные.
https://sass-lang.com/documentation/variables

2021-03-26 14:21 UTC, vladsmit commented on frontend/src/assets/icons/SearchIcon.jsx
> +export default SearchIcon;
Предлагаю это поместить в папку компонентов, а не assets

2021-03-26 14:23 UTC, awesomesk1ll commented on frontend/src/components/ThemeButton.jsx
> +      style={ {
Обязательно стараться все стили выносить в css, т.к. у нас переключение тёмной темы скорее всего будет завязано на добавление класса dark.

2021-03-26 14:24 UTC, TamaraBogantseva commented on frontend/src/components/ThemeButton.jsx
> +      style={ {
Я сюда просто залезла, чтобы margin лишний убрать, верстку ломал) Но раз уж залезла, давайте переделаю

2021-03-26 14:24 UTC, vladsmit commented on frontend/src/pages/Home/index.js
> +import page from './Home.jsx';
а этот файл какой функционал несет?

2021-03-26 14:25 UTC, awesomesk1ll commented on frontend/src/assets/icons/SearchIcon.jsx
> +export default SearchIcon;
можно наверное `components/icons/<вот сюда>`

2021-03-26 15:00 UTC, awesomesk1ll commented on frontend/src/pages/Home/style.scss
> +      fill: #DA952D;
https://codesandbox.io/s/sass-variables-in-react-0tumj?file=/src/colors.module.scss:75-97
и
https://codesandbox.io/s/github/Microflash/remarkability/tree/master/?file=/scss/_variables.scss

2021-03-26 17:14 UTC, awesomesk1ll approved these changes

2021-03-26 17:30 UTC, vladsmit approved these changes

2021-03-26 17:32 UTC, merged

2021-03-27 12:28 UTC, Faustova commented
reviewed