Login reg page
awesomesk1ll/gotfilm.tk pull request #14
Opened 2021-03-27 09:31 UTC by shiryaev585

2021-03-28 09:00 UTC, vladsmit commented
3 конфликта нужно поправить

2021-03-28 09:05 UTC, vladsmit commented on frontend/src/pages/RegPage/RegPage.jsx
> +            message: "Пожалуйста подтвертите введённый пароль!",
подтверДите

2021-03-28 09:08 UTC, vladsmit commented on frontend/src/store/index.js
> +window.store = store;
а это для чего используется? Чтобы иметь глобальный доступ к стору?

2021-03-28 09:11 UTC, vladsmit requested changes
По коду всё ок, пару моментов прокомментировал только и несколько конфликтов необходимо поправить

2021-03-30 05:39 UTC, TamaraBogantseva requested changes
Вроде все ок, нужно только разрешить конфликты

2021-03-30 08:25 UTC, merged