Navbar
awesomesk1ll/gotfilm.tk pull request #20
Opened 2021-04-01 15:25 UTC by shiryaev585

1. Добавил компоненты Navbar, FilmLists и HamburgerMenu. FilmLists в виде заготовки пока что. Там только меню и заголовок. С кастомизацией стилей компонентов андизайна пока не разобрался. Если кто-то в курсе - пишите)
2. Подправил имена формам регистрации и логинизации как @idoleg вчера указал.

2021-04-01 19:04 UTC, awesomesk1ll requested changes
Так, ничего не понимаю. Нужно разбить пуллреквест на несколько в зависимости от какая фича добавляется. ПР называется Navbar, а по факту тут тебе и навбар, и регистрация, и каталог, и то и это. Какая-то лапша.

2021-04-01 19:04 UTC, awesomesk1ll commented on frontend/src/components/HamburgerMenu/HamburgerMenu.jsx
> +const HamburgerMenu = (props) => {
Что это за компонент? его в дизайне вроде не было

2021-04-01 19:04 UTC, awesomesk1ll commented on frontend/src/components/Navbar/Navbar.jsx
> +        <form className="navbar__desktop-form">
Что за поиск? Зачем он?

2021-04-01 19:04 UTC, awesomesk1ll commented on frontend/src/components/Navbar/Navbar.jsx
> +        <Link className="navbar__desktop-item login" to="/login">
Это тут зачем? Кнопка логина нужна только на странице настроек.

2021-04-01 19:04 UTC, awesomesk1ll commented on frontend/src/pages/Catalog.jsx
>  const Catalog = (props) => {
Каталог?

2021-04-02 07:54 UTC, shiryaev585 commented on frontend/src/pages/Catalog.jsx
>  const Catalog = (props) => {
Каталог уже убрал

2021-04-02 07:55 UTC, shiryaev585 commented on frontend/src/components/HamburgerMenu/HamburgerMenu.jsx
> +const HamburgerMenu = (props) => {
Был. Скину скрин в телегу

2021-04-02 07:58 UTC, shiryaev585 commented on frontend/src/components/Navbar/Navbar.jsx
> +        <form className="navbar__desktop-form">
Это для десктопной навигации. Ноя так понимаю, что она будет кардинально переделываться, если вообще будет. В любом случае у нас в навигации согласно макету предусмотрен поиск

2021-04-02 08:06 UTC, shiryaev585 commented on frontend/src/components/Navbar/Navbar.jsx
> +        <Link className="navbar__desktop-item login" to="/login">
Ок. Мне её тогда удалить? И из моб и из десктоп версии

2021-04-03 09:52 UTC, awesomesk1ll commented on frontend/src/components/Navbar/Navbar.jsx
> +        <form className="navbar__desktop-form">
Поиск там не предусмотрен

2021-04-04 11:15 UTC, closed without merging