lists from localStorage and add clearAction for settings
awesomesk1ll/gotfilm.tk pull request #42
Opened 2021-04-14 14:47 UTC by vladsmit

1) Обновил компонент Settings, добавил в него метод handleClearSettings, который зачищает пока что только состояние списков (blacklistFilms и alreadySeenFilms в store + local storage), а также подключил к компоненту store.
В последствии можно повесить на данный экшен сброс других настроек, когда они будут перенесены в store.

Сам компонент теперь является контейнером, поэтому нужно всю верстку убрать в отдельный компонент-отрисовщик, а также не забыть передать в него все пропсы, которыми аппелирует верстка.

2) При загрузке приложения, помимо подтягивания фильмов из JSON, подтягивается состояние списков (просмотренные, черный список) из local storage.

3) Убрал persist из приложения.

Еще буду дорабатывать корректную запись состояния списков в local storage, сейчас данные записываются, но не совсем так, как нужно.

2021-04-19 17:33 UTC, shiryaev585 submitted a review, later dismissed

2021-04-21 16:53 UTC, awesomesk1ll requested changes

2021-04-21 16:53 UTC, awesomesk1ll commented on frontend/src/containers/FilmCardContainer.jsx
> +    blacklistFilms: PropTypes.object,
А зачем списки сами понадобились в этом компоненте ?
Смотрится, что они здесь не нужны.

2021-04-27 08:34 UTC, vladsmit commented on frontend/src/containers/FilmCardContainer.jsx
> +    blacklistFilms: PropTypes.object,
Почему не нужны, мы ведь должны всегда синхронизировать состояние списков с тем, что у нас хранится в local storage. И при внесении в список очередного фильма, мы обновляем состояние local storage, что при перезагрузке страницы подгрузились актуальные списки

2021-04-27 09:40 UTC, adrienrosselet submitted a review, later dismissed

2021-04-28 13:56 UTC, TamaraBogantseva approved these changes

2021-04-28 15:31 UTC, merged